### ISSUE TITLE
Error after training starts: "type object got multiple values for keyword argument 'max_t' " 

### ISSUE THREAD

**Issue by TomasMendozaHN** [jkulhanek/visual-navigation-agent-pytorch#4]
**I am using Ubuntu16.04. I follow the steps you specified to start training. Shortly after the text  "training started" shows, i get the error "type object got multiple values for keyword argument 'max_t'". You can see my terminal output below:**

Status: Downloaded newer image for kulhanek/visual-navigation-agent-pytorch:latest
Training started
Traceback (most recent call last):
  File "/app/train.py", line 39, in <module>
    t.run()
  File "/app/agent/training.py", line 243, in run
    self.threads = [_createThread(i, task) for i, task in enumerate(branches)]
  File "/app/agent/training.py", line 243, in <listcomp>
    self.threads = [_createThread(i, task) for i, task in enumerate(branches)]
  File "/app/agent/training.py", line 241, in _createThread
    **self.config)
TypeError: type object got multiple values for keyword argument 'max_t'

**What can i do? I didn't change anything in your code, just cloned it from github and executed it like your instructions.**

**Comment by pushkalkatara** [comment]
Hi @tmendozarias , were you able to resolve this issue?

**Comment by cenotence** [comment]
I think this problem is occurred because max_t assigned twice in training.py file.  

So comment out or deleat Ln 29 'max_t' :5, in training.py, where assign default_config.

> DEFAULT_CONFIG = {
>     'saving_period': 10 ** 6 // 5,
>     'checkpoint_path': 'model/checkpoint-{checkpoint}.pth',
>     'grad_norm': 40.0,
>     'gamma': 0.99,
>     'entropy_beta': 0.01,
>     #'max_t': 5,
> }

this worked for me.
