### ISSUE TITLE
KeyError: "Unable to open object (object 'hitting_times' doesn't exist)"

### ISSUE THREAD

**Issue by cenotence** [jkulhanek/visual-navigation-agent-pytorch#5]
**I have got following error messages. I would be grateful if anyone could teach me. Thanks**

```
Traceback (most recent call last):
  File "./eval.py", line 21, in <module>
    t.run()
  File "/app/agent/evaluation.py", line 109, in run
    hitting_times = graph['hitting_times'][()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'hitting_times' doesn't exist)"
```

-FYI-
Clearly, there is no hitting_times in h5py file as follows.
>>> with h5py.File('./data/bathroom_02.h5', 'r') as f:
...     print(f.keys())
... 
<KeysViewHDF5 ['graph', 'location', 'observation', 'resnet_feature', 'rotation', 'shortest_path_distance']>

**Comment by yang-yz716** [comment]
How do you solve this problem? Thank you very much！

**Comment by jkulhanek** [comment]
Sorry for my late response. Take a look at this notebook: https://github.com/jkulhanek/visual-navigation-agent-pytorch/blob/ad92b6d2519137cb72963795578ff7125eb0f310/Untitled.ipynb

**Comment by cenotence** [comment]
Thank you very much!! it is solved now! 

But I am just wondering why these data are not contained in original training data??
Is it possible to train model without hitting_time?? And then why it requires hitting_time when it's evaluation. Thank you.

**Comment by yang-yz716** [comment]
Thank you very much!!

**Comment by jkulhanek** [comment]
I used hitting_times for a different evaluation metric (from different paper). Therefore, you don’t need it and you can comment it out. I don’t believe it is used during training, but I haven’t checked.
