### ISSUE TITLE
FileExistsError: [Errno 17] File exists

### ISSUE THREAD

**Issue by Yi-Zhang-git** [jkulhanek/visual-navigation-agent-pytorch#8]
I have got following error messages. I would be grateful if anyone could teach me. Thanks

/home/zy/anaconda3/envs/icra2017/lib/python3.8/site-packages/ai2thor/controller.py:1214: UserWarning: start method depreciated. The server started when the Controller was initialized.
  warnings.warn(
Traceback (most recent call last):
  File "/home/zy/reproduce/visual-navigation-agent-pytorch-master_2/explorer.py", line 54, in <module>
    Explorer(**args).show()
  File "/home/zy/reproduce/visual-navigation-agent-pytorch-master_2/explorer.py", line 14, in __init__
    self.env.reset()
  File "/home/zy/reproduce/visual-navigation-agent-pytorch-master_2/agent/environment/thor.py", line 23, in reset
    self._initialize()
  File "/home/zy/reproduce/visual-navigation-agent-pytorch-master_2/agent/environment/thor.py", line 16, in _initialize
    self.controller.start()
  File "/home/zy/anaconda3/envs/icra2017/lib/python3.8/site-packages/ai2thor/controller.py", line 1226, in start
    self.server.start()
  File "/home/zy/anaconda3/envs/icra2017/lib/python3.8/site-packages/ai2thor/fifo_server.py", line 203, in start
    os.mkfifo(self.server_pipe_path)
FileExistsError: [Errno 17] File exists

**Comment by jkulhanek** [comment]
Please report this problem in the ai2thor repository: https://github.com/allenai/ai2thor.
